### ISSUE TITLE
RnDAO main Database 

### ISSUE THREAD

**Issue by mehrdadmms** [RnDAO/tc-dbComm#1]
# Goal
All of the information that might not relate to one specific DAO's data will go to this database such as users and configurations 

# How 
- [ ] Create mongoDB schema for the specified collection and database
- [ ] Do the ground work for creating a package in order to use in other projects 
- [ ] Setup Mongoose ODM 

# More Details
## Schema 
- ********************Database:******************** RnDAO
    - **Collection**: *Users*
        - UserDiscordId
        - ServersWithAdminPermission
        - Email
        - CreatedAt
        - PhoneNumber
        - AccountLevel
        - AvatarLink
    - ************************Collection:************************ *Settings*
        - UserDiscordId,
        - ServerDiscordId,
        - ServerName
        - SelectedChannels
            - ChannelDiscordId
            - ChannelName
        - Period
        - CreatedAt

**Comment by Behzad-rabiei** [comment]
Hi, I m working on this issue.
It will be finished on December 7.

**Comment by mehrdadmms** [comment]
Closed by #3
