### ISSUE TITLE
Store server's data schema

### ISSUE THREAD

**Issue by mehrdadmms** [RnDAO/tc-dbComm#2]
# Goal
For each server we need to create a separate DB to store their information. this helps us control the size of the data and easily aggregate the data. 

# How
- [ ] Functionality create new DB schema for each new server (should ignore if already exists)
- [x] Define the schema for raw information
- [x] Create the Schema for storing raw information
- [x] Create the schema for storing heat map objects 

# More details
## Schema
- **Database:** Create one database for each server’s information
    - ************************Collection:************************ Raw data
    - **Collection**: Heatmap data
        - **Schema →**
        `{date: DATE:”Date of the document”,channel: STRING:”the channel this document belongs to”,messages: ARRAY:[List of the number of messages per hour for that channel (including threads)],interactions: ARRAY:[List of the number of interactions per hour for that channel],emojis: ARRAY:[List of the number of emojis per hour for that channel]}`
        - **Example →**
        `
        {
    date: “2022 - 07 - 01”,
    channel: “Human vibez”,
    messages: [0, 1, 1, 1, 2, 0, 0, 1, 1, 0, 1, 0, 2, 0, 4, 3, 1, 2, 0, 1, 0, 1, 0, 2],
    interactions: [0, 1, 1, 1, 2, 0, 0, 1, 1, 0, 1, 0, 2, 0, 4, 3, 1, 2, 0, 1, 0, 1, 0, 2],
    emojis: [0, 1, 1, 1, 2, 0, 0, 1, 1, 0, 1, 0, 2, 0, 4, 3, 1, 2, 0, 1, 0, 1, 0, 2]
}
        `

**Comment by magicpalmtree** [comment]
Schema for raw information.

Schema→
{
  Id: unsigned integer: "message id",
  Type: string: "type of message" (default or reply or guild member or something),
  Created_At: Datetime: "date time of message",
  Author: string: "author of message",
  Content: string: "content of message",
  User_Mentions: String Array: "list of mentioned users",
  Roles_Mentions: String Array: "list of mentioned roles",
  Reactions: String Array: "list of reactions",
  Replied_User: String: "replied message user",
  Reference_Message: unsigned integer: "replied message id"
}

Example →
{
  Id: 1050125843017519104,
  Type: "REPLY",
  Created_At: "7 Dec 2022 14:5:11",
  Author: "Boda#2954",
  Content: "Message Here",
  User_Mentions: [Beshoy#5456,Sortoite#2577],
  Roles_Mentions: [Surrpot],
  Reactions: [❤️],
  Replied_User: "Sortoite#2577",
  Reference_Message: 1050119122215780352
}
