### ISSUE TITLE
Add codeclimate badges to README.md

### ISSUE THREAD

**Issue by cyri113** [RnDAO/tc-dbComm#55]
Badges will provide us with a quick overview of the status.

@daniel-ospina Tasks:
- [x] Follow instructions (https://docs.codeclimate.com/docs/overview#badges)
- [x] We want the **Markdown** version of the badges for both **Maintainability** and **Testing**.
- [x] Paste code as a comment in this issue

developer Tasks:
- [x] Add both badges to the Readme.md file

**Comment by daniel-ospina** [comment]
[![Maintainability](https://api.codeclimate.com/v1/badges/52d516c2ad7c262adb37/maintainability)](https://codeclimate.com/github/RnDAO/tc-dbComm/maintainability)


[![Test Coverage](https://api.codeclimate.com/v1/badges/52d516c2ad7c262adb37/test_coverage)](https://codeclimate.com/github/RnDAO/tc-dbComm/test_coverage)
